### ISSUE TITLE
Warning: could not load entry point flatly 

### ISSUE THREAD

**Issue by COLABORATI** [ralphbean/flatly#1]
Hi, I am just trying to understand what pyramid does, however I get this error with flatly:

Warning: could not load entry point flatly (ImportError: No module named flatly)
Unavailable scaffolds: ['flatly']

I installed with pip install flatly without errors, but then pcreate does not work the expected way. Why?

**Comment by ralphbean** [comment]
Ah, there was a bug in the way flatly was packaged.  I just uploaded flatly-0.3 to pypi.  Can you reinstall it and try again?
